---
version: '3'

tasks:
  default:
    desc: "default: build"
    deps: [build]

  build:
    desc: Build the gallerygen program for the local machine
    cmds:
      - mkdir -p out
      - go build -ldflags "-X main.Version=$(./.version.sh)" -o out/gallerygen .
    sources:
      - "*.go"
      - "go.mod"
      - "go.sum"
      - ".version.sh"
    generates:
      - out/gallerygen

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf out
